/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif






int main(void)
{

	volatile uint32_t *RCC_AHB1ENR =(volatile uint32_t*)0x40023830;
	*RCC_AHB1ENR |= (1<<0);

	volatile uint32_t *RCC_APB1ENR =(volatile uint32_t*)0x40023840;
	*RCC_APB1ENR |= (1<<1);




	volatile uint32_t *GPIO_MODDER = (volatile uint32_t*)0x40020000;
	*GPIO_MODDER &= ~(3<<12);
	*GPIO_MODDER |=  (2<<12);

	volatile uint32_t *GPIOA_AFRL = (volatile uint32_t*)0x40020020;
	*GPIOA_AFRL &= ~(15<<24);
	*GPIOA_AFRL |=  (2<<24);

	volatile uint32_t *TIM3_PSC = (volatile uint32_t*)0x40000428;
	*TIM3_PSC = 15;

	volatile uint32_t *TIM3_ARR = (volatile uint32_t*)0x4000042C;
	*TIM3_ARR = 9999;

	volatile uint32_t *TIM3_CCR1 = (volatile uint32_t*)0x40000434;
//	*TIM3_CCR1 = 990;

	volatile uint32_t *TIM3_CCMR1 = (volatile uint32_t*)0x40000418;
	*TIM3_CCMR1 |= (6 << 4);

	volatile uint32_t *TIM3_CCER = (volatile uint32_t*)0x40000420;
	*TIM3_CCER |= (1 << 0);

	volatile uint32_t *TIM3_CR1 = (volatile uint32_t*)0x40000400;
	*TIM3_CR1 |= (1 << 0);

//	volatile uint32_t *systic_CSR = (volatile uint32_t *)0xE000E010;
//
//	volatile uint32_t *systic_RVR = (volatile uint32_t *)0xE000E014;
//	volatile uint32_t *systic_CVR = (volatile uint32_t *)0xE000E018;
//
//	*systic_CVR = 0;
//	*systic_RVR = 15999;
//	*systic_CSR |= (7<<0);



	for(;;){
		for( uint32_t i =10000; i>0; i--){
			*TIM3_CCR1 = i;

			for(volatile uint32_t delay = 0; delay < 20000; delay++) {}
		}

		for( uint32_t i=0; i<10000; i++){
			*TIM3_CCR1 =i;

			for(volatile uint32_t delay=0; delay <20000; delay++){}

		}

	}
}
