/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


volatile uint32_t *GPIOA_ODR = (volatile uint32_t*)0x40020014;

volatile uint32_t *EXTI4_PR = (volatile uint32_t*)0x40013C14;


volatile uint32_t SYStic_count =0;

void SysTick_Handler(void){
	SYStic_count++;
}

void EXTI4_IRQHandler(void){

	static uint32_t last_time =0;
	if(SYStic_count-last_time>50){
		*GPIOA_ODR ^= (1<<6);
		last_time = SYStic_count;
	}
	*EXTI4_PR= (1<<4) ;
}




int main(void)
{

	volatile uint32_t *RCC_AHB1ENR =(volatile uint32_t*)0x40023830;
	*RCC_AHB1ENR &= ~(17<<0);
	*RCC_AHB1ENR |= (17<<0);

	volatile uint32_t *RCC_APB1ENR =(volatile uint32_t*)0x40023840;
	*RCC_APB1ENR |= (1<<1);

	volatile uint32_t *RCC_APB2ENR =(volatile uint32_t*)0x40023844;
	*RCC_APB2ENR |= (1<<14);


	volatile uint32_t *GPIOE_MODDER = (volatile uint32_t*)0x40021000;
	*GPIOE_MODDER &= ~(3<<8);

	volatile uint32_t *GPIOE_PUPDR = (volatile uint32_t*)0x4002100C;
	*GPIOE_PUPDR &= ~(3<<8);
	*GPIOE_PUPDR |= (1<<8);

	volatile uint32_t *SYSCFG_EXTICR2 = (volatile uint32_t*)0x4001380C;
	*SYSCFG_EXTICR2 &= ~(4<<0);
	*SYSCFG_EXTICR2 |= (4<<0);

	volatile uint32_t *EXTI4_IMR = (volatile uint32_t*)0x40013C00;
	*EXTI4_IMR |= (1<<4);

	volatile uint32_t *EXTI4_FTSR = (volatile uint32_t*)0x40013C0C;
	*EXTI4_FTSR |= (1<<4);

	volatile uint32_t *EXTI4_RTSR = (volatile uint32_t*)0x40013C08;
	*EXTI4_RTSR &= ~(1<<4);

	volatile uint32_t *NVIC_ISER0 = (volatile uint32_t*)0xE000E100;
	*NVIC_ISER0 |= (1<<10);

	volatile uint32_t *GPIOA_MODDER = (volatile uint32_t*)0x40020000;
	*GPIOA_MODDER &= ~(3<<12);
	*GPIOA_MODDER |=  (1<<12);

	*GPIOA_ODR |= (1<<6);

	volatile uint32_t *systic_CSR = (volatile uint32_t *)0xE000E010;

	volatile uint32_t *systic_RVR = (volatile uint32_t *)0xE000E014;
	volatile uint32_t *systic_CVR = (volatile uint32_t *)0xE000E018;

	*systic_CVR = 0;
	*systic_RVR = 15999;
	*systic_CSR |= (7<<0);



	for(;;){

	}
}
